language: java

sudo: false

services:
  - xvfb

install: true

env:
  global:
    - secure: "UVIbeoJpx9n0KSWHbpdWZuR4zeZfXw3JQBq2Zb1h0/j4uREfXWiGFuNVQBPjsdtYi2+LkecjJ/MgKWo+SS0SjsvTa/ZPkOXt4408H1qYgwVnvWoeL/g1QQ6T8ADNysl/4ZtJLnSp0WXYEBkfHYZJD++vgDwkpVhnCLVzSFVAHls="

before_install:
  - openssl aes-256-cbc -K $encrypted_01456a3862ee_key -iv $encrypted_01456a3862ee_iv -in ./ci/id_rsa.key.enc -out /tmp/id_rsa.key -d
  - chmod 600 /tmp/id_rsa.key
  - export JDK="openjdk14"
  #Installs the normal openjdk as this is not supported by travis itself
  - chmod +x ./ci/installjdk.sh && ./ci/installjdk.sh
  - export JAVA_HOME="~/$JDK"
  - export JAVA_TOOL_OPTIONS="-Dprism.verbose=true -Dprism.order=sw"
  - export JAVA_TOOL_OPTIONS="-Dprism.verbose=true -Dprism.order=sw"
  - export APP_VERSION=$([ -n "${TRAVIS_TAG}" ] && echo "${TRAVIS_TAG#*v}" || echo "${TRAVIS_BRANCH##*/}")
  - export GITHUB_RELEASE_VERSION=$([ -n "${TRAVIS_TAG}" ] && echo "${TRAVIS_TAG}" || echo "${TRAVIS_BRANCH##*/}")

before_script:
  - export PATH="$JAVA_HOME/bin:$PATH"

script:
  - echo "$JAVA_HOME"
  - echo "$PATH"
  - java -version
  - chmod +x ./ci/build.sh && ./ci/build.sh
  - chmod +x ./ci/test.sh && ./ci/test.sh
  - chmod +x ./ci/test-report.sh && ./ci/test-report.sh

after_success:
  - if [ -n "${TRAVIS_TAG}" ]; then chmod +x ./ci/github-release.sh && ./ci/github-release.sh; fi
  - chmod +x ./ci/publish-update4j.sh && ./ci/publish-update4j.sh
  - cp build/update4j/win/*/update4j.xml build/update4j/update4i-win.xml
  - cp build/update4j/unix/*/update4j.xml build/update4j/update4i-unix.xml

after_failure:
- cat /home/travis/build/FAForever/downlords-faf-client/hs_err_pid*.log

deploy:
  provider: releases
  api_key: ${gitHubToken}
  file_glob: true
  file:
  - build/install4j/*.exe
  - build/install4j/*.msi
  - build/install4j/*.zip
  - build/install4j/*.gz
  - build/install4j/*.deb
  - build/install4j/*.rpm
  - build/update4j/update4i-*.xml
  skip_cleanup: true
  name: ${GITHUB_RELEASE_VERSION}
  draft: true
  prerelease: true
  # Doesn't yet work, see https://github.com/travis-ci/dpl/issues/155
  #  body: ${RELEASE_BODY}
  # See https://github.com/travis-ci/travis-ci/issues/8248
  target_commitish: ${TRAVIS_COMMIT}
  tag_name: ${TRAVIS_TAG}
  on:
    tags: true

addons:
  apt:
    packages:
    - unzip
    - python3
  coverity_scan:
    project:
      name: "micheljung/downlords-faf-client"
      description: "A high quality re-implementation of the Forged Alliance Forever client"
    notification_email: michel.jung89@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew build"
    branch_pattern: coverity_scan

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/install4j/
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - ~/.install4j8
  - /home/travis/build/FAForever/downlords-faf-client/build/cache/
  - ~/openjdk14