language: java

jdk:
- oraclejdk10

sudo: false

install: true

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Download install4j and the required JRE, only if it doesn't already exist (from cache)
  - if [ ! -d "$HOME/install4j/install4j7.0.7" -a -n "${TRAVIS_TAG}" ]; then
      mkdir -p "$HOME/install4j" &&
      curl https://download-keycdn.ej-technologies.com/install4j/install4j_unix_7_0_7.tar.gz -o "$HOME/install4j/install4j.tar.gz" &&
      mkdir -p "$HOME/install4j/install4j7.0.7/jres/" &&
      curl http://content.faforever.com/jre/windows-amd64-10.0.2.tar.gz -o "$HOME/install4j/install4j7.0.7/jres/windows-amd64-10.0.2.tar.gz" &&
      tar xzf "$HOME/install4j/install4j.tar.gz" -C "$HOME/install4j";
    fi
  - VERSION=$([ -z "${TRAVIS_TAG}" ] && echo "${TRAVIS_TAG#*v}" || echo "${TRAVIS_BRANCH##*/}")

script:
- ./gradlew --stacktrace check

after_success:
  - ./gradlew jacocoTestReport coveralls
  - if [ -n "${TRAVIS_TAG}" ]; then
      ./gradlew --stacktrace -Pversion=${VERSION} -Pinstall4jHomeDir="$HOME/install4j/install4j7.0.7" -Pinstall4jLicense=${install4jLicense} buildInstall4jMediaFiles &&
    RELEASE_BODY=$(python build-release-body.py ${VERSION}) &&
    echo "Release body\n:${RELEASE_BODY}"
    fi

deploy:
  provider: releases
  api_key: ${gitHubToken}
  file_glob: true
  file:
    - build/install4j/*.exe
    - build/install4j/*.zip
    - build/install4j/*.gz
    - build/install4j/*.deb
    - build/install4j/*.rpm
  skip_cleanup: true
  name: v${VERSION}
  draft: true
  prerelease: true
  # Doesn't yet work, see https://github.com/travis-ci/dpl/issues/155
  #  body: ${RELEASE_BODY}
  on:
    tags: true

env:
  global:
   - secure: "UVIbeoJpx9n0KSWHbpdWZuR4zeZfXw3JQBq2Zb1h0/j4uREfXWiGFuNVQBPjsdtYi2+LkecjJ/MgKWo+SS0SjsvTa/ZPkOXt4408H1qYgwVnvWoeL/g1QQ6T8ADNysl/4ZtJLnSp0WXYEBkfHYZJD++vgDwkpVhnCLVzSFVAHls="

addons:
  coverity_scan:
    project:
      name: "micheljung/downlords-faf-client"
      description: "A high quality re-implementation of the Forged Alliance Forever client"
    notification_email: michel.jung89@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew build"
    branch_pattern: coverity_scan

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/install4j/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - /home/travis/build/FAForever/downlords-faf-client/build/cache/
