language: java

sudo: false

install: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
- ./gradlew test jacocoTestReport coveralls

env:
  global:
   - secure: "UVIbeoJpx9n0KSWHbpdWZuR4zeZfXw3JQBq2Zb1h0/j4uREfXWiGFuNVQBPjsdtYi2+LkecjJ/MgKWo+SS0SjsvTa/ZPkOXt4408H1qYgwVnvWoeL/g1QQ6T8ADNysl/4ZtJLnSp0WXYEBkfHYZJD++vgDwkpVhnCLVzSFVAHls="

addons:
  apt:
    packages:
      - oracle-java8-installer

  coverity_scan:
    project:
      name: "micheljung/downlords-faf-client"
      description: "A high quality re-implementation of the Forged Alliance Forever client"
    notification_email: michel.jung89@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew build"
    branch_pattern: coverity_scan
