faf-client:
  true-skill:
    initialStandardDeviation: 500
    initialMean: 1500
    beta: 240
    dynamic-factor: 10
    draw-probability: 0.1

  links:
    linksTecHelpDiscord: https://discord.gg/BMDMUKS
    linksTecHelpForum: https://forum.faforever.com/category/4/i-need-help
    linksRules: ${faf-client.website.base-url}/rules
    linksModerationReport: ${faf-client.website.base-url}/account/report
    linksFacebook: https://www.facebook.com/ForgedAllianceForever/
    linksDevNews: https://faforeverdevblog.tumblr.com
    linksYoutube: https://www.youtube.com/channel/UCkAWiUu4QE172kv-ZuyR42w

  vault:
    map_rules_url: https://forum.faforever.com/topic/323/faf-map-vault-rules-regulations
    mod_rules_url: https://forum.faforever.com/topic/607/faf-mod-vault-rules-regulations
    map_validation_url: ${faf-client.api.base-url}/maps/validate
    mapDownloadUrlFormat: ${faf-client.vault.base-url}/maps/%s.zip
    mapPreviewUrlFormat: ${faf-client.vault.base-url}/maps/previews/%s/%s.png

  website:
    report-url: ${faf-client.website.base-url}/account/report
    news-hub-url: ${faf-client.website.base-url}/newshub

  imgur:
    upload:
      clientId: 141ee8a7030f16d

  unit-database:
    spookiesUrl: https://faforever.github.io/spooky-db/#/
    rackOversUrl: https://unitdb.faforever.com?settings64=eyJwcmV2aWV3Q29ybmVyIjoiTm9uZSJ9

  vanillaGameHashes:
    - 1AFBCD0CA85546470660FA8AC09B230E870EC65C8D1B33FEB6731BB5D4C366C5

  map-generator:
    repoAndOwnerName: FAForever/Neroxis-Map-Generator
    queryLatestVersionUrl: https://api.github.com/repos/${faf-client.map-generator.repoAndOwnerName}/releases/latest
    queryVersionsUrl: https://api.github.com/repos/${faf-client.map-generator.repoAndOwnerName}/releases
    downloadUrlFormat: https://github.com/${faf-client.map-generator.repoAndOwnerName}/releases/download/%1$s/NeroxisGen_%1$s.jar
    maxSupportedMajorVersion: 1
    minSupportedMajorVersion: 0

  translation-project-url: https://poeditor.com/join/project/2oWfdaZQZj
  client-config-url: https://content.faforever.com/dfc-config.json
  client-config-connect-timeout: 10s
  show-ice-adapter-debug-Window: ${SHOW_ICE_ADAPTER_DEBUG_WINDOW:false}

  discord:
    discord_prerelease_feedback_channel_url: https://discord.gg/fZc4BsE
    application_id: 464069837237518357
    small_image_key: faf_logo_small
    big_image_key: faf_logo_big
    join-url: https://discord.gg/PfGcWas

  statping:
    api-root: https://status.faf.micheljung.ch/api

spring:
  profiles:
    active: ${CLIENT_PROFILE:prod}
  application:
    name: Downlord's FAF Client
  main:
    web-application-type: none
  codec:
    max-in-memory-size: 16MB

logging:
  level:
    org.springframework.beans: warn
    org.springframework.http.client.support: info
    org.springframework.web.client: info
    org.springframework.security.oauth2: info
    org.springframework.security.oauth2.client.token.grant: off

    org.ice4j.stack: warn
    com.nbarraille.jjsonrpc: warn

    com.faforever.client.FafClientApplication: info
    com.faforever.client.api: info
    com.faforever.client.connectivity: info
    com.faforever.client.chat: info
    com.faforever.client.preferences: info
    com.faforever.client.map: info
    com.faforever.client.mod: info
    com.faforever.client.net: info
    com.faforever.client.util: info
    com.faforever.client.patch: info
    com.faforever.client.events: info
    com.faforever.client.legacy: info
    com.faforever.client.remote: info
    com.faforever.client.replay: info
    com.faforever.client.relay: info
    com.faforever.client.game: info
    com.faforever.client.task: info
    com.faforever.client.theme: info
    com.faforever.client.io: info
    com.faforever.client.os: info
    com.faforever.client.fa.relay.ice: info
    com.faforever.client.fx: info
  config: classpath:logback-spring.xml
