faf-client:
  server:
    host: lobby.test.faforever.com
    port: 8001

  irc:
    host: irc.test.faforever.com
    port: 6697

  vault:
    base-url: https://content.test.faforever.com
    replay-download-url-format: https://replay.test.faforever.com/%s

  news:
    feed-url: https://direct.test.faforever.com/news/feed

  replay:
    remote-host: test.faforever.com
    remote-port: 15000

  website:
    base-url: https://www.test.faforever.com

  api:
    base-url: https://api.test.faforever.com
    client-id: 3bc8282c-7730-11e5-8bcf-feff819cdc9f
    client-secret: 6035bd78-7730-11e5-8bcf-feff819cdc9f

  oauth:
    base-url: https://hydra.test.faforever.com
    scopes: openid offline public_profile upload_map upload_mod lobby
    client-id: faf-java-client

  forged-alliance:
    exe-url: https://content.test.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe
