faf-client:
  server:
    host: lobby.test.faforever.com

  irc:
    host: irc.test.faforever.com

  ice:
    turn:
      host: test.faforever.com
    stun:
      host: test.faforever.com

  vault:
    base-url: http://content.test.faforever.com

  news:
    feed-url: http://direct.faforever.com/news/feed

  replay:
    remote-host: test.faforever.com

  website:
    base-url: https://www.test.faforever.com

  api:
    base-url: http://api.test.faforever.com
    client-id: 3bc8282c-7730-11e5-8bcf-feff819cdc9f
    client-secret: 6035bd78-7730-11e5-8bcf-feff819cdc9f

  forged-alliance:
    exe-url: http://content.test.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe
