faf-client:
  true-skill:
    initialStandardDeviation: 500
    initialMean: 1500
    beta: 240
    dynamic-factor: 10
    draw-probability: 0.1

  vault:
   mapDownloadUrlFormat: ${faf-client.vault.base-url}/faf/vault/maps/%s.zip
   mapPreviewUrlFormat: ${faf-client.vault.base-url}/faf/vault/map_previews/%s/%s.png
   replayDownloadUrlFormat: ${faf-client.vault.base-url}/faf/vault/replay_vault/replay.php?id=%s
   modDownloadUrlFormat: ${faf-client.vault.base-url}/faf/vault/maps/%s.zip

  website:
      forgot-password-url: ${faf-client.website.base-url}/account/password/reset
      create-account-url: ${faf-client.website.base-url}/account/register

  imgur:
    upload:
      clientId: 141ee8a7030f16d

  unit-database:
    spookiesUrl: http://spooky.github.io/unitdb/#/
    rackOversUrl: http://direct.faforever.com/faf/unitsDB/?settings64=eyJwcmV2aWV3Q29ybmVyIjoiTm9uZSJ9

  map-generator:
    repoAndOwnerName: FAForever/Neroxis-Map-Generator
    queryLatestVersionUrl: https://api.github.com/repos/${faf-client.map-generator.repoAndOwnerName}/releases/latest
    downloadUrlFormat: https://github.com/${faf-client.map-generator.repoAndOwnerName}/releases/download/%1$s/NeroxisGen_%1$s.jar


  translation-project-url: https://poeditor.com/join/project/2oWfdaZQZj
  client-config-url: http://content.faforever.com/dfc-config.json
  client-config-connect-timeout: 10s
  show-ice-adapter-debug-Window: ${SHOW_ICE_ADAPTER_DEBUG_WINDOW:false}

  discord:
    application_id: 464069837237518357
    small_image_key: faf_logo_small
    big_image_key: faf_logo_big

spring:
  profiles:
    active: ${CLIENT_PROFILE:prod}
  main:
    web-environment: false
  application:
    name: Downlord's FAF Client

security:
  oauth2:
    client:
      clientAuthenticationScheme: header
logging:
  level:
    org.springframework.beans: warn
    org.springframework.http.client.support: info
    org.springframework.web.client: info
    org.springframework.security.oauth2: info
    org.springframework.security.oauth2.client.token.grant: off
    faf-ice-adapter: info

    org.ice4j.stack: warn
    com.nbarraille.jjsonrpc: warn
    org.pircbotx: warn

    com.faforever.client.FafClientApplication: info
    com.faforever.client.api: info
    com.faforever.client.connectivity: info
    com.faforever.client.chat: info
    com.faforever.client.preferences: info
    com.faforever.client.map: info
    com.faforever.client.mod: info
    com.faforever.client.net: info
    com.faforever.client.util: info
    com.faforever.client.patch: info
    com.faforever.client.events: info
    com.faforever.client.legacy: info
    com.faforever.client.remote: info
    com.faforever.client.replay: info
    com.faforever.client.relay: info
    com.faforever.client.game: info
    com.faforever.client.task: info
    com.faforever.client.theme: info
    com.faforever.client.io: info
    com.faforever.client.os: info
    com.faforever.client.fa.relay.ice: info
    com.faforever.client.fx: info
